In [1]:
import pandas as pd

df = pd.read_csv('US_Accidents_Dec21_updated.csv', parse_dates=['Start_Time'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845342 entries, 0 to 2845341
Data columns (total 47 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Severity               int64
 2   Start_Time             datetime64[ns]
 3   End_Time               object
 4   Start_Lat              float64
 5   Start_Lng              float64
 6   End_Lat                float64
 7   End_Lng                float64
 8   Distance(mi)           float64
 9   Description            object
 10  Number                 float64
 11  Street                 object
 12  Side                   object
 13  City                   object
 14  County                 object
 15  State                  object
 16  Zipcode                object
 17  Country                object
 18  Timezone               object
 19  Airport_Code           object
 20  Weather_Timestamp      object
 21  Temperature(F)         float64
 22  Wind_Chill(F)          float64
 23  Humidity(%)            float64
 24  Pressure(in)           float64
 25  Visibility(mi)         float64
 26  Wind_Direction         object
 27  Wind_Speed(mph)        float64
 28  Precipitation(in)      float64
 29  Weather_Condition      object
 30  Amenity                bool
 31  Bump                   bool
 32  Crossing               bool
 33  Give_Way               bool
 34  Junction               bool
 35  No_Exit                bool
 36  Railway                bool
 37  Roundabout             bool
 38  Station                bool
 39  Stop                   bool
 40  Traffic_Calming        bool
 41  Traffic_Signal         bool
 42  Turning_Loop           bool
 43  Sunrise_Sunset         object
 44  Civil_Twilight         object
 45  Nautical_Twilight      object
 46  Astronomical_Twilight  object
dtypes: bool(13), datetime64[ns](1), float64(13), int64(1), object(19)
memory usage: 773.4+ MB

In [2]:
df.tail()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
2845337,A-2845338,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.00248,-117.37936,33.99888,-117.37094,0.543,At Market St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845338,A-2845339,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.76696,-117.14806,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845339,A-2845340,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.77545,-117.84779,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,False,Day,Day,Day,Day
2845340,A-2845341,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.99246,-118.40302,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845341,A-2845342,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.13393,-117.23092,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
df2 = df[(pd.to_datetime('7/1/2021', dayfirst=True) >= df.Start_Time) & ( df.Start_Time >= pd.to_datetime('1/1/2021'))]

In [4]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18387 entries, 439760 to 2069159
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     18387 non-null  object
 1   Severity               18387 non-null  int64
 2   Start_Time             18387 non-null  datetime64[ns]
 3   End_Time               18387 non-null  object
 4   Start_Lat              18387 non-null  float64
 5   Start_Lng              18387 non-null  float64
 6   End_Lat                18387 non-null  float64
 7   End_Lng                18387 non-null  float64
 8   Distance(mi)           18387 non-null  float64
 9   Description            18387 non-null  object
 10  Number                 8792 non-null   float64
 11  Street                 18387 non-null  object
 12  Side                   18387 non-null  object
 13  City                   18387 non-null  object
 14  County                 18387 non-null  object
 15  State                  18387 non-null  object
 16  Zipcode                18382 non-null  object
 17  Country                18387 non-null  object
 18  Timezone               18368 non-null  object
 19  Airport_Code           18287 non-null  object
 20  Weather_Timestamp      17992 non-null  object
 21  Temperature(F)         17903 non-null  float64
 22  Wind_Chill(F)          17836 non-null  float64
 23  Humidity(%)            17854 non-null  float64
 24  Pressure(in)           17977 non-null  float64
 25  Visibility(mi)         17853 non-null  float64
 26  Wind_Direction         17907 non-null  object
 27  Wind_Speed(mph)        17907 non-null  float64
 28  Precipitation(in)      17415 non-null  float64
 29  Weather_Condition      17950 non-null  object
 30  Amenity                18387 non-null  bool
 31  Bump                   18387 non-null  bool
 32  Crossing               18387 non-null  bool
 33  Give_Way               18387 non-null  bool
 34  Junction               18387 non-null  bool
 35  No_Exit                18387 non-null  bool
 36  Railway                18387 non-null  bool
 37  Roundabout             18387 non-null  bool
 38  Station                18387 non-null  bool
 39  Stop                   18387 non-null  bool
 40  Traffic_Calming        18387 non-null  bool
 41  Traffic_Signal         18387 non-null  bool
 42  Turning_Loop           18387 non-null  bool
 43  Sunrise_Sunset         18351 non-null  object
 44  Civil_Twilight         18351 non-null  object
 45  Nautical_Twilight      18351 non-null  object
 46  Astronomical_Twilight  18351 non-null  object
dtypes: bool(13), datetime64[ns](1), float64(13), int64(1), object(19)
memory usage: 5.1+ MB

In [5]:
df.Start_Time.max()

Timestamp('2021-12-31 23:30:00')

In [6]:
df2.Start_Time.min()

Timestamp('2021-01-01 00:00:00')

In [7]:
df2.to_csv('finalworkingdata2.csv')